spring.application.name=RUB-Daten-Evaluator
smb.host=10.150.5.185
smb.port=445
smb.share=Shared
smb.path=preProd
smb.username=samba
smb.password=secret
smb.outputPath=Validierungsberichte
smb.validDatPath=ValideDaten

camel.main.run-controller=true

terminology-server-url=https://tx.fhir.org/r4
